### ISSUE TITLE
Proposal: expose scrape timeout information to scripts and optionally enforce it

### ISSUE THREAD

**Issue by siebenmann** [ricoberger/script_exporter#11]
When Prometheus makes a scrape, it exposes information about the scrape timeout in a special HTTP header, which is used by Blackbox to set timeouts for its probes (other exporters may also use it, I'm not sure). I propose exposing this information to scripts in some environment variables and optionally having `script_exporter` enforce this by using `exec.CommandContext` with a `Context` that has a deadline (on the grounds that this saves people from having to wrap various scripts in a boilerplate `timeout $SCRIPT_TIMEOUT cmd ...`).

If this is of interest, I've put together a branch with an implementation of this: https://github.com/siebenmann/script_exporter/tree/script-timeouts

I've split the implementation into two commits (first adding the environment variables, then adding the optional enforcement) in case you'd like to not have the optional enforcement side. There's also a tiny cleanup of command line argument handling. I can revise any or all of these, or make a pull request, as you'd like.

**Comment by ricoberger** [comment]
One question: Is it really necessary to have the timeout configuration also in the configuration file of the script_exporter. I think it is enough, if only the timeout from Prometheus is used, or did I oversee something?

**Comment by siebenmann** [comment]
I did it because this imitates what Blackbox does, and I can see some point to having a maximum timeout, no matter what Prometheus tells you. Prometheus normally derives the scrape timeouts from the scrape interval, unless you tell specifically configure them otherwise, and for mixed tests you may know that some Blackbox modules or script tests either succeed or fail much faster than others, so you might as well have them fail early so that Prometheus finds out about problems fast. You can manually configure a scrape timeout in Prometheus, but then you need different configuration stanzas for different tests that need different timeouts instead of being able to put them all in one stanza with some clever rewriting rules.

(The case we've run into with Blackbox is ICMP pings. On our local network, if a ping doesn't succeed almost immediately, it never will, and even off-network pings aren't going to succeed after ten seconds or so. Meanwhile, we have some places we ping infrequently, so the natural Prometheus scrape timeout is 50 seconds or more.)

I admit that one reason for doing this here is that I already knew I needed a new section for configuring whether or not timeouts would be enforced. So I wasn't adding a new section, just a new field.

Also, this raises an issue: should I change it so that `timeout` is not a sub-section of the script configuration, and you just specify `max_timeout` and `enforced` directly, along side the existing `name` and `script`? In hindsight, that would simplify things a bit for writing configurations, and the code basically wouldn't notice. (I was too taken with reusing the same structure for `timeouts` and the per-script `timeout` when I wrote the current code.)

**Comment by ricoberger** [comment]
I would prefer the solution to have the `timeout` section (with `max_timeout` and `enforce`) only along the `name` and `script`. Then the configured scrape timeout from Prometheus is used as default and if needed we can configure a script specific timeout.

PS: Thanks for your fantastic work.

**Comment by siebenmann** [comment]
I've now updated my https://github.com/siebenmann/script_exporter/tree/script-timeouts branch tree to drop the global 'timeouts' section in the configuration file, keeping only a 'timeout' sub-section in per-script settings. Let me know if this looks good and is what you want.

(I did it as an extra commit on top of the current three, rather than going back to re-do the first two commits.)

**Comment by ricoberger** [comment]
Looks good. Feel free to create a PR.
