### ISSUE TITLE
Race condition when cache duration is set for a script.

### ISSUE THREAD

**Issue by ebusto** [ricoberger/script_exporter#157]
Access to the cache map is unsynchronized, so there's a race condition whenever the cache duration for a script is set.

This is easy to reproduce if you use the `-race` flag when building or running the exporter, and fire up a couple of `curl` commands that run constantly in parallel.

**Comment by ricoberger** [comment]
Hi @ebusto thanks for reporting the issue. This should be fixed by #166.
