### ISSUE TITLE
Script failed: fork/exec, exec format error

### ISSUE THREAD

**Issue by lozbrown** [ricoberger/script_exporter#17]
Hi 

Can anyone help me understand why this fails 
> $ /app/dvkdbhk/home/dvkdbhkx/REPOS/lbrown15/kdb-data-services/lbrown15/script/sh/metrics/latency_by_exchange
> #HELP latency_by_exchange Average Latency by exchange for the last 30 seconds
> #TYPE latency_by_exchange gauge
> latency_by_exchange{exchange="CU2", host="unycasd20556"} 0.6871429
> latency_by_exchange{exchange="DTB", host="unycasd20556"} 0.7325
> latency_by_exchange{exchange="EUX", host="unycasd20556"} 0.324
> latency_by_exchange{exchange="ICE", host="unycasd20556"} 0.5640802
> latency_by_exchange{exchange="LIF", host="unycasd20556"} 646.997
> latency_by_exchange{exchange="LME", host="unycasd20556"} 5332.213
> latency_by_exchange{exchange="OSA", host="unycasd20556"} 0.3487727
> 
> $ ./script_exporter-v2.0.1-linux-amd64 -config.file ./script_exporter.yml -web.listen-address :4522
> Starting server (version=v2.0.1, branch=master, revision=92a7645e2e084df7334b71a17b65eb04bbda0e5c)
> Build context (go=go1.13.4, user=ricoberger, date=20191213-09:08:44)
> script_exporter listening on :4522
> 2020/03/18 05:14:20 Script failed: fork/exec /app/dvkdbhk/home/dvkdbhkx/REPOS/lbrown15/kdb-data-services/lbrown15/script/sh/metrics/latency_by_exchange: exec format error

**Comment by ricoberger** [comment]
Hi @lozbrown, can you share the `script_exporter.yml` and your script `latency_by_exchange`?

Without it is very difficult to say, whats going wrong here. Maybe it is a problem with the file permissions of the script. Also ensure, that you include a shebang in your script or change the script_exporter config to use sth. like the following:

```yaml
scripts:
  - name: latency_by_exchange
    script: /bin/bash /app/dvkdbhk/home/dvkdbhkx/REPOS/lbrown15/kdb-data-services/lbrown15/script/sh/metrics/latency_by_exchange
```

**Comment by lozbrown** [comment]
IT was the shebang that was not in the top line, this solved it. Thanks
