### ISSUE TITLE
missing port in address

### ISSUE THREAD

**Issue by lehy786** [ricoberger/script_exporter#18]
hello, i got trouble in running the exporter with a specific port.
when i use the cmd `./script_exporter -config.file config.yml -web.listen-address 19469`, there's error msg shows "address 19469: missing port in address", 
and i change the line into `./script_exporter -config.file config.yml -web.listen-address 127.0.0.1:19469`, the exporter seems working, but i cant access the "host:port/metrics" from a browser, please help!
thanks!!

**Comment by lehy786** [comment]
Worked out.
change the 127.0.0.1 into real ip.

**Comment by ricoberger** [comment]
Hi @lehy786, nice to here that you solved your problem. It looks like that there is a `:` missing in your first command. When you change this to the following it should also work:

```sh
./script_exporter -config.file config.yml -web.listen-address :19469
```
