### ISSUE TITLE
How to run scripts for windows?

### ISSUE THREAD

**Issue by sanindd** [ricoberger/script_exporter#24]
Hi, what scripts can I use on win. I tried to use python script in title  #! python but got an error Script parameter is missing.
scripts:
  - name: my_script
    script: C:\my_script.py

What am I doing wrong?

**Comment by ricoberger** [comment]
Hi @sanindd, the error **Script parameter is missing.** indicates that the `script` parameter is missing. When you open the following url the error shouldn't occur and your should get the result of your script: `http://localhost:9469/probe?script= my_script`

**Comment by sanindd** [comment]
Yes thank you. What does this error mean? %1 is not a valid Win32 application.

**Comment by sanindd** [comment]
I figured out my mistake. thank)
