### ISSUE TITLE
impossible to launch a windows service from script_exporter-windows-amd64.exe

### ISSUE THREAD

**Issue by adjosan** [ricoberger/script_exporter#31]
I create  a windows service with sc.exe and i try to start the service, error 1053 appears  "The service did not respond to start or control request in a timely fashion"

It's seem that it missing in script_exporter.go informations for Service Control Manager. It does not receive a "service started" notice from the service within this time-out period.

Is it possible to fix it ?

**Comment by ricoberger** [comment]
Hi @adjosan, thanks for reporting. Unfortunately I haven't a windows system at the moment.

I can try to come up with a solution by following the example, but would need some help for testing. Is it ok for you, if I add you to a PR for testing?

**Comment by adjosan** [comment]
Hi, yes you can .

**Comment by skpenpen** [comment]
I did the windows service compatible version#32

**Comment by ricoberger** [comment]
Hi this feature should available in version [2.4.0](https://github.com/ricoberger/script_exporter/releases/tag/v2.4.0). Thanks again @skpenpen for the implementation.
