### ISSUE TITLE
Windows Powershell or CMD script example

### ISSUE THREAD

**Issue by YulianSalo** [ricoberger/script_exporter#41]
@ricoberger I would be grateful if you could provide some examples for Windows scripts (powershell/cmd)

**Comment by skpenpen** [comment]
tls:
  enabled: false
  crt: server.crt
  key: server.key

basicAuth:
  enabled: false
  username: username
  password: password

bearerAuth:
  enabled: false
  signingKey: my_secret_key

scripts:

  - name: hello
    script: powershell -executionpolicy bypass -file C:/Prometheus/script_exporter/scripts/helloworld.ps1

  - name: hyperv
    script: powershell -executionpolicy bypass -file C:/Prometheus/script_exporter/scripts/hyperv.ps1

  - name: scheduled_tasks
    script: powershell -executionpolicy bypass -file C:/Prometheus/script_exporter/scripts/scheduled_tasks.ps1

  - name: certificats
    script: powershell -executionpolicy bypass -file C:/Prometheus/script_exporter/scripts/cert.ps1

  - name: synchronisation_ntp
    script: powershell -executionpolicy bypass -file C:/Prometheus/script_exporter/scripts/synchronisation_ntp.ps1 -ntpserver <ntpserver>

**Comment by ricoberger** [comment]
Thanks for sharing @skpenpen.

Does this help you @YulianSalo and @m-marinka?

**Comment by ricoberger** [comment]
Since the issue seems to be resolved, I would close it for now. If you need further help please let me know or if someone ones to add an example for PowerShell / CMD feel free to create a PR.
