### ISSUE TITLE
alpine lacks bash?

### ISSUE THREAD

**Issue by bbeattie-phxlabs** [ricoberger/script_exporter#45]
The first line of the Dockerfile sources `FROM golang:1.17-alpine3.14 as build`, which lacks bash. As such:

```
# docker run --rm -it --entrypoint /bin/bash ricoberger/script_exporter:v2.5.0
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
```

Yet all the examples provided use bash (e.g. https://github.com/ricoberger/script_exporter/blob/master/examples/ping.sh).

Am I missing something here?

**Comment by ricoberger** [comment]
Hi @bbeattie-phxlabs, yes you are right the examples are not working because bash is missing in the Docker image.

I created a PR (#46) to add bash to the Docker image and tested that the examples are working now within the Docker image.
