### ISSUE TITLE
how to use output?can u give me a demo ?thx!!!

### ISSUE THREAD

**Issue by Eleven-CZ** [ricoberger/script_exporter#48]
`scripts:
  - name: test_running
    script: /apps/scripts/test.sh
    output: /apps/scripts/output.txt
    timeout:
      max_timeout: 60
`
it's useless

**Comment by ricoberger** [comment]
Hi @Eleven-CZ, there is no `output` property in the script configuration. An example configuration can be found [here](https://github.com/ricoberger/script_exporter/blob/master/examples/config.yaml).

**Comment by ricoberger** [comment]
I would close the issue for now. If you need further help with the configuration please let me know.
