### ISSUE TITLE
Update Dockerfile to fix CRITICAL vulnerabilities linked to the used version of the base image

### ISSUE THREAD

**Issue by khaoulaB1** [ricoberger/script_exporter#49]
**Name and Version**
ricoberger/script_exporter:v2.1.1

**What is the problem this feature will solve?**
This feature will solve secutiry critical vulnerabilities, below the trivy scan :

For ricoberger/script_exporter:v2.1.1 that uses:
-	base image : alpine:3.10 
-	build image : golang:1.13-alpine3.10
![image](https://user-images.githubusercontent.com/47610975/165748922-9ce5a158-f902-412d-89d6-4b5d00a57e98.png)

**What is the feature you are proposing to solve the problem?**
Update Dockerfile using: 
-	base image :  alpine:3.11.12
-	build image : golang:1.13-alpine3.11

Below the trivy scan for the suggested build and base images: 

![image](https://user-images.githubusercontent.com/47610975/165750449-a0c5702e-3eec-452d-bd46-206f7b0d62e0.png)

**Comment by ricoberger** [comment]
Hi @khaoulaB1, thanks for reporting.

I updated the used Go version to 1.18 and the base images and the trivy scan doesn't report any vulnerabilities now:

```
2022-04-30T12:00:19.676+0200    INFO    Detected OS: alpine
2022-04-30T12:00:19.676+0200    INFO    Detecting Alpine vulnerabilities...
2022-04-30T12:00:19.684+0200    INFO    Number of language-specific files: 1
2022-04-30T12:00:19.684+0200    INFO    Detecting gobinary vulnerabilities...

ricoberger/script_exporter:latest (alpine 3.15.4)
=================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)


bin/script_exporter (gobinary)
==============================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
