### ISSUE TITLE
RFE: Support directly running scripts and switch to it by default

### ISSUE THREAD

**Issue by siebenmann** [ricoberger/script_exporter#5]
Currently, the script exporter runs specified scripts by invoking the specified shell (``/bin/sh`` by default) with the command line arguments ``script [arg ...]``. The problem with this is that it is very easy to believe that you can specify a binary executable as the ``script:`` setting (a belief that is encouraged by two out of the three examples starting with ``#! /bin/bash``). This doesn't work, and in fact it fails explosively; some shells will try to interpret your binary executable as a shell script and all sorts of crazy things proceed to happen.

I propose two changes (and I can submit a pull request to implement one or both). First, support directly running programs, instead of invoking the shell, by setting an empty shell on the command line: ``script_exporter -config.shell ""``. Second, make this the default and require people to specifically set the shell (even to /bin/sh) if they want the behavior of running through the shell.

(This requires only minor changes because ``exec.Command()`` already pretty much supports this usage; you just run ``args[0]`` instead of ``*shell``, with small other changes.)

**Comment by ricoberger** [comment]
Sounds like a very useful improvement. I will take a look at this in the upcoming days. If you want to submit a PR your welcome.
