### ISSUE TITLE
When the script exits with non-0 code, output is not provided to prometheus

### ISSUE THREAD

**Issue by mvalo** [ricoberger/script_exporter#63]
Hello, 

Unless mistaking in the way to use the exporter, when the script exits with non-0 return code, its output it not provided to prometheus. 
I believe it comes from here : https://github.com/ricoberger/script_exporter/blob/main/pkg/exporter/metrics.go#L67

Example OK : 
```
[~]# cat script_exiting_0
#!/bin/bash
echo "EXIT 0"
exit 0
[~]# 
[~]# curl -s "http://0:9469/probe?script=script_exiting_0"
# HELP script_success Script exit status (0 = error, 1 = success).
# TYPE script_success gauge
script_success{script="script_exiting_0"} 1
# HELP script_duration_seconds Script execution time, in seconds.
# TYPE script_duration_seconds gauge
script_duration_seconds{script="script_exiting_0"} 0.011737
# HELP script_exit_code The exit code of the script.
# TYPE script_exit_code gauge
script_exit_code{script="script_exiting_0"} 0
EXIT 0
```

Example NOK : 
```
[~]# cat script_exiting_1
#!/bin/bash
echo "EXIT 1"
exit 1
[~]# 
[~]# curl -s "http://0:9469/probe?script=script_exiting_1"
# HELP script_success Script exit status (0 = error, 1 = success).
# TYPE script_success gauge
script_success{script="script_exiting_1"} 0
# HELP script_duration_seconds Script execution time, in seconds.
# TYPE script_duration_seconds gauge
script_duration_seconds{script="script_exiting_1"} 0.002808
# HELP script_exit_code The exit code of the script.
# TYPE script_exit_code gauge
script_exit_code{script="script_exiting_1"} 1
```

**Comment by ricoberger** [comment]
Hi @mvalo, this is the expected behavior.

What you can do is to catch the exit code of your command within the script and export a custom metric `my_command_exit_code <EXIT CODE>`.

I'm a bit afraid of changing this behavior because a lot of our scripts would break when they leave the happy path, because the output will not be properly formatted anymore.

**Comment by mvalo** [comment]
Hello @ricoberger 
if the script fails (even if error is caught), to me it's not natural to exit with 0. 
I'm not sure to understand your relunctancy to change this. 
Would it be possible to let me open a PR for you to see my changes ? then of course it's up to you, the script owner, to merge it or not :)

**Comment by ricoberger** [comment]
Hi @mvalo, you can fork the repository and create a PR from your fork. I will review it then 🙂

**Comment by mvalo** [comment]
@ricoberger here it is : https://github.com/ricoberger/script_exporter/pull/67
