### ISSUE TITLE
Using scrape config with discovery does not trigger the scripts

### ISSUE THREAD

**Issue by OranShuster** [ricoberger/script_exporter#69]
Using the following scrape config in prometheus
```
      - job_name: 'script-exporter-discovery'
        http_sd_configs:
          - url: http://script-exporter-svc:9469/discovery
```

i can see the script_success and all the rest of the "basic" metrics but the script itself does not get triggered

**Comment by ricoberger** [comment]
Hi @OranShuster, when the `script_success` metrics is present, it means that the script was executed. Is the `script_success` metric `1`? If the `script_success` metric is `0` it means that the script execution failed and then the exported metrics from the script are omitted (see #63).
