### ISSUE TITLE
Include `jq` in the Docker image

### ISSUE THREAD

**Issue by AlexDaichendt** [ricoberger/script_exporter#70]
Hey! 

I was creating scripts that parse a REST API with `jq`. I was wondering if it was possible to include `jq` in the default docker image, since its a fairly standard tool to parse json in bash scripts. 

Obviously, I can build my own image, but perhaps more people could profit / save time if some common standard scripting tools are shipped with a docker image.

Thank you in advance for creating and maintaining this project :)

**Comment by ricoberger** [comment]
Hi @AlexDaichendt, thanks for your suggestion 🙂. Version 2.9.0 should contain `jq`.

**Comment by AlexDaichendt** [comment]
Wonderful, thank you for the quick action :)
