### ISSUE TITLE
Proposal: provide internal Prometheus metrics for script_exporter

### ISSUE THREAD

**Issue by siebenmann** [ricoberger/script_exporter#8]
The Prometheus Blackbox exporter both answers your probes with probe-specific metrics and provides additional internal metrics for its own state. Right now, script_exporter has no equivalent of the latter, and I think having it would be potentially handy, especially if the standard Go client metrics were augmented with metrics about what script_exporter is doing and has done so that you could see things like how many scripts were currently active.

I've put together a preliminary version of this to show what I'm thinking of, at https://github.com/siebenmann/script_exporter/tree/internal-metrics. The metrics are always exposed on ``/metrics``; the code arranges to share this URL path with the script handler if necessary. I can further develop this into something worth a pull request if you're interested.

(Changing the default script handler path away from ``/metrics`` to, say, ``/probe``, is probably too much of a breaking change. It turned out to be easy enough to share the two based on whether or not there are URL query parameters.)

**Comment by ricoberger** [comment]
Sorry for the late reply. I like the idea to export some metrics for the script_exporter. After a first look I would go with the changes in your `internal-metrics` branch. If you want to create a pull request, your welcome.

The only thing I would change is the endpoint. Like you mentioned, I would prefer the logic of the Blackbox exporter. So that the metrics are exposed on `/metrics` and the scripts on `/probe`.

Also if it's a breaking change, I think the effort to adjust the Prometheus configuration is not as that much. I would also like to get ride of the `shell` flag, so maybe these two changes can be done in one release.

**Comment by siebenmann** [comment]
If the endpoint is going to change, should it be hard-coded to ``/probe``, dropping the ``-web.telemetry-path`` flag entirely? That matches the behavior of Blackbox, which doesn't give you any choice, and would simplify the code.

Should I try to figure out how to protect the metrics endpoint with authentication via ``use()``? If not, can I take authentication off the front page as well, since the metrics endpoint exposes the same build information (apart from builduser)?

**Comment by ricoberger** [comment]
Yes, removing the `web.telemetry-path` flag should be the best option.

Personally, I would like to see it if the `/metrics` and `/probe` endpoints are protected via authentication, but honestly I only used this feature once. Usually the authentication can also be happen via a reverse proxy. What's your opinion?

**Comment by siebenmann** [comment]
One reason I'm reluctant to touch authentication for ``/metrics`` is that it would need code changes to the authentication setup code, and I don't have any way of really testing that. I could probably get it correct just from the types being right, but 'probably correct' is not what I like for security related code.

(Currently ``use()`` requires you to pass it a ``http.HandlerFunc``, but what we get from Prometheus for the metrics endpoint is a ``http.Handler``. The least awkward change is to modify the ``use()`` related stuff, but that's a change to the authentication code.)

**Comment by ricoberger** [comment]
I see, let's go without authentication. I will take a look at this.
