### ISSUE TITLE
script-exporter does not handle process reaping, leaving zombie processes behind

### ISSUE THREAD

**Issue by diversario** [ricoberger/script_exporter#92]
I'm running it in Kubernetes, and use `kubectl`, `jq` etc to get the data to produce a metric. I noticed that the script execution fails intermittently with the script getting killed, even though it did not meet the timeout or logged any errors.

The I noticed this in the container:

```
script-exporter-5dd8cbfc8-xjv7r:$ ps faux
PID   USER     TIME  COMMAND
    1 nobody    0:07 /bin/script_exporter -config.file /etc/script-exporter/script-exporter.yml
 3300 nobody    0:00 [kubectl]
 3700 nobody    0:00 [kubectl]
 3798 nobody    0:00 [kubectl]
 3996 nobody    0:00 [kubectl]
 4900 nobody    0:00 [kubectl]
 6894 nobody    0:00 [kubectl]
 7895 nobody    0:00 [kubectl]
15302 nobody    0:00 [jq]
...

script-exporter-5dd8cbfc8-xjv7r:$ cat /proc/3300/status
Name:   kubectl
State:  Z (zombie)
Tgid:   3300
...
```

dozens of zombie processes sitting around. Perhaps script-exporter should run under `tini` or something else that handles reaping defunct processes? This is in containerd, by the way, which seemingly [does not handle this](https://github.com/containerd/containerd/issues/4594) the way Docker does.

**Comment by diversario** [comment]
I got around the issue by building a custom image:

```Dockerfile
FROM ricoberger/script_exporter:v2.14.1 as exporter

RUN apk add --no-cache tini

USER nobody

ENTRYPOINT ["/sbin/tini", "--", "/bin/script_exporter"]
```

**Comment by ricoberger** [comment]
Hi @diversario is this a general solution and if so do you want to make a PR for it?

**Comment by diversario** [comment]
This would apply to anyone running the script-exporter container not in Docker, such as the more recent k8s version (iirc 1.20+).

With Docker this will also work - it just adds a little unnecessary layer, but it doesn't hurt. I can PR the Dockerfile change, yes.
